//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipwayUnitOfWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignWork
    {
        public int AssignWorkId { get; set; }
        public string ExhibitionId { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<System.DateTime> AssignWorkDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Note { get; set; }
    
        public virtual Exhibition Exhibition { get; set; }
        public virtual Users Users { get; set; }
    }
}
