//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipwayUnitOfWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShipwayDbEntities : DbContext
    {
        public ShipwayDbEntities()
            : base("name=ShipwayDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agency { get; set; }
        public virtual DbSet<AssignWork> AssignWork { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<Exhibition> Exhibition { get; set; }
        public virtual DbSet<ExhibitionStatus> ExhibitionStatus { get; set; }
        public virtual DbSet<HistoryTrip> HistoryTrip { get; set; }
        public virtual DbSet<KindService> KindService { get; set; }
        public virtual DbSet<KindTimeReceived> KindTimeReceived { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Router> Router { get; set; }
        public virtual DbSet<ServiceCharge> ServiceCharge { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeUsers> TypeUsers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Ward> Ward { get; set; }
    }
}
