//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipwayUnitOfWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exhibition()
        {
            this.AssignWork = new HashSet<AssignWork>();
            this.HistoryTrip = new HashSet<HistoryTrip>();
        }
    
        public string ExhibitionId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhoneNumber { get; set; }
        public string ReceiverAddress { get; set; }
        public string WardReceiveId { get; set; }
        public Nullable<int> PackageWeigh { get; set; }
        public Nullable<int> PackageLong { get; set; }
        public Nullable<int> PackageWide { get; set; }
        public Nullable<int> PackageHigh { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedUserId { get; set; }
        public Nullable<int> KindServiceId { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> ExhibitionStatusId { get; set; }
        public Nullable<System.DateTime> DayReceive { get; set; }
        public string LocationSender { get; set; }
        public string LocationReceive { get; set; }
        public Nullable<bool> IsSendToAgency { get; set; }
        public Nullable<int> AssignToAgencyId { get; set; }
        public Nullable<int> GroupLump { get; set; }
        public Nullable<int> NumberOfFailedDeliveries { get; set; }
        public Nullable<int> AgencyId { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Agency Agency1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignWork> AssignWork { get; set; }
        public virtual Users Users { get; set; }
        public virtual KindService KindService { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        public virtual Ward Ward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryTrip> HistoryTrip { get; set; }
    }
}
