//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipwayUnitOfWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryTrip
    {
        public int HistoryTripId { get; set; }
        public string ExhibitionId { get; set; }
        public Nullable<System.DateTime> DateTrip { get; set; }
        public Nullable<int> ExhibitionStatusId { get; set; }
        public string CurrentAddress { get; set; }
        public string Note { get; set; }
    
        public virtual Exhibition Exhibition { get; set; }
        public virtual ExhibitionStatus ExhibitionStatus { get; set; }
    }
}
