//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipwayUnitOfWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCharge
    {
        public int ServiceChargeId { get; set; }
        public Nullable<int> RouterId { get; set; }
        public Nullable<int> KindServiceId { get; set; }
        public Nullable<int> KindTimeReceivedId { get; set; }
        public Nullable<int> CostOderUrban { get; set; }
        public Nullable<int> CostOderSubUrban { get; set; }
        public Nullable<int> AddWeight { get; set; }
        public Nullable<int> AddMoney { get; set; }
        public Nullable<int> Weight { get; set; }
    
        public virtual KindService KindService { get; set; }
        public virtual KindTimeReceived KindTimeReceived { get; set; }
        public virtual Router Router { get; set; }
    }
}
